[project]
name = "gesture-dino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cvzone>=1.6.1",
    "mediapipe>=0.10.21",
    "opencv-contrib-python>=4.11.0.86",
    "opencv-python>=4.11.0.86",
]
